import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

export type CopyText = {
  id: string;
  description: string;
  content: string;
};

// Import patterns that indicate a file uses the copy system
const COPY_IMPORTS: { module: string; name: string }[] = [
  { module: "copy/t", name: "t" },
  { module: "copy/use-copy", name: "useCopy" },
  { module: "copy-ids", name: "CopyId" },
];

(async () => {
  const textMap = new Map<string, CopyText>();
  const srcDir = path.join(__dirname, "../src");
  const files = await findSourceFiles(srcDir);

  for (const file of files) {
    parseFile(file, textMap);
    console.log(`Parsed ${file}, found ${textMap.size} texts`);
  }

  await writeOutput(textMap);
})();

// ── File discovery ──────────────────────────────────────────────────

async function findSourceFiles(dir: string): Promise<string[]> {
  const results: string[] = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await findSourceFiles(full)));
    } else if (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) {
      results.push(full);
    }
  }
  return results;
}

// ── Output generation ───────────────────────────────────────────────

async function writeOutput(textMap: Map<string, CopyText>) {
  const values = [...textMap.values()];
  const generatedDir = path.join(__dirname, "../src/generated");

  await fs.writeFile(
    path.join(generatedDir, "copy.json"),
    JSON.stringify(values, null, 2),
  );

  const cids = values.map((v) => `  | ${JSON.stringify(v.id)}`).join("\n");
  const typeFile = `// Auto-generated by extracty-copy.ts — do not edit manually\nexport type CopyId =\n${cids};\n`;
  await fs.writeFile(path.join(generatedDir, "copy-ids.ts"), typeFile);

  console.log(`Generated copy-ids.ts with ${values.length} CIDs`);
}

// ── AST parsing ─────────────────────────────────────────────────────

function parseFile(file: string, textMap: Map<string, CopyText>) {
  const source = ts.sys.readFile(file, "utf8");
  if (!source) return;

  const kind = file.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS;
  const sourceFile = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, kind);
  const hasCopyImport = fileImportsCopy(sourceFile);

  ts.forEachChild(sourceFile, function walk(node) {
    tryExtractTextJsx(node, sourceFile, textMap);
    if (hasCopyImport) tryExtractTCall(node, textMap);
    ts.forEachChild(node, walk);
  });
}

/** Check if the file imports from the copy system */
function fileImportsCopy(sourceFile: ts.SourceFile): boolean {
  return sourceFile.statements.some((stmt) => {
    if (!ts.isImportDeclaration(stmt)) return false;
    if (!ts.isStringLiteral(stmt.moduleSpecifier)) return false;
    const mod = stmt.moduleSpecifier.text;
    const bindings = stmt.importClause?.namedBindings;
    if (!bindings || !ts.isNamedImports(bindings)) return false;
    return COPY_IMPORTS.some(
      (ci) => mod.includes(ci.module) && bindings.elements.some((el) => el.name.text === ci.name),
    );
  });
}

// ── Extractors ──────────────────────────────────────────────────────

/** Extract copy from `<Text cid="..." fallback="...">` or `<Text cid="...">children</Text>` */
function tryExtractTextJsx(node: ts.Node, sourceFile: ts.SourceFile, textMap: Map<string, CopyText>) {
  if (!ts.isJsxOpeningElement(node) && !ts.isJsxSelfClosingElement(node)) return;
  if (node.tagName.getText() !== "Text") return;

  const attr = (name: string) => getStrAttr(node, name, sourceFile);
  const cid = attr("cid");
  const description = attr("description");
  const fallback = attr("fallback") ?? (ts.isJsxOpeningElement(node) && getChildrenText(node));

  if (!cid) return warn("<Text> missing cid");
  if (!fallback) return warn("<Text> missing fallback");
  if (!description) warn("<Text> missing description");

  upsert(textMap, cid, fallback || "", description ?? "");
}

/** Extract copy from `t("cid", "fallback")` or `t("cid", "fallback", "description")` */
function tryExtractTCall(node: ts.Node, textMap: Map<string, CopyText>) {
  if (!ts.isCallExpression(node)) return;
  if (!ts.isIdentifier(node.expression) || node.expression.text !== "t") return;

  const args = node.arguments;
  if (args.length < 2) return;
  if (!ts.isStringLiteral(args[0]) || !ts.isStringLiteral(args[1])) return;

  const cid = args[0].text;
  const fallback = args[1].text;
  const description = args.length >= 3 && ts.isStringLiteral(args[2]) ? args[2].text : "";

  upsert(textMap, cid, fallback, description);
}

// ── Helpers ─────────────────────────────────────────────────────────

/** Insert or update — keeps the entry with the longest description */
function upsert(textMap: Map<string, CopyText>, id: string, content: string, description: string) {
  const prev = textMap.get(id);
  if (!prev || prev.description.length < description.length) {
    textMap.set(id, { id, description, content });
  }
}

function getStrAttr(node: ts.JsxOpeningLikeElement, name: string, sourceFile: ts.SourceFile): string | undefined {
  for (const attr of node.attributes.properties) {
    if (
      ts.isJsxAttribute(attr) &&
      attr.name.getText(sourceFile) === name &&
      attr.initializer &&
      ts.isStringLiteral(attr.initializer)
    ) {
      return attr.initializer.text;
    }
  }
  return undefined;
}

function getChildrenText(node: ts.JsxOpeningElement): string | undefined {
  const parent = node.parent;
  if (!ts.isJsxElement(parent)) return undefined;
  const textChildren = parent.children.filter(ts.isJsxText);
  if (textChildren.length === 1) return textChildren[0].text.trim();
  return undefined;
}

function warn(msg: string) {
  console.warn(`⚠ ${msg}`);
}
