import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

export type CopyText = {
  id: string;
  description: string;
  content: string;
};

const TextMap = new Map<string, CopyText>();

(async () => {
  const srcDir = path.join(__dirname, "../src");
  const files = await findSourceFiles(srcDir);
  for (const file of files) {
    await parseFile(file, TextMap);
    console.log(`Parsed ${file}, found ${TextMap.size} texts`);
  }

  const values = [...TextMap.values()];
  const output = JSON.stringify(values, null, 2);
  const generatedDir = path.join(__dirname, "../src/generated");
  await fs.writeFile(path.join(generatedDir, "copy.json"), output);

  // Generate type-safe CID union
  const cids = values.map((v) => `  | ${JSON.stringify(v.id)}`).join("\n");
  const typeFile = `// Auto-generated by extracty-copy.ts — do not edit manually\nexport type CopyId =\n${cids};\n`;
  await fs.writeFile(path.join(generatedDir, "copy-ids.ts"), typeFile);
  console.log(`Generated copy-ids.ts with ${values.length} CIDs`);
})();

async function findSourceFiles(dir: string): Promise<string[]> {
  const files = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const file of entries) {
    if (file.name === "." || file.name === "..") continue;
    if (file.isFile() && (file.name.endsWith(".tsx") || file.name.endsWith(".ts"))) {
      files.push(path.join(dir, file.name));
      continue;
    }
    if (file.isDirectory()) {
      files.push(...(await findSourceFiles(path.join(dir, file.name))));
    }
  }
  return files;
}

async function parseFile(file: string, textMap: Map<string, CopyText>) {
  const source = await fs.readFile(file, "utf8");
  const kind = file.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS;
  const sourceFile = ts.createSourceFile(
    file,
    source,
    ts.ScriptTarget.Latest,
    true,
    kind,
  );
  // Only scan for t() calls in files that import from the copy system (useCopy or CopyId)
  const importsCopy = sourceFile.statements.some((stmt) => {
    if (!ts.isImportDeclaration(stmt) || !ts.isStringLiteral(stmt.moduleSpecifier)) return false;
    const mod = stmt.moduleSpecifier.text;
    if (!mod.includes("copy/use-copy") && !mod.includes("copy-ids")) return false;
    const bindings = stmt.importClause?.namedBindings;
    if (!bindings || !ts.isNamedImports(bindings)) return false;
    return bindings.elements.some((el) => el.name.text === "useCopy" || el.name.text === "CopyId");
  });

  walk(sourceFile);

  function walk(node: ts.Node) {
    // Detect <Text cid="..." ...>fallback</Text>
    if (ts.isJsxOpeningElement(node) || ts.isJsxSelfClosingElement(node)) {
      const tagname = node.tagName.getText();
      if (tagname === "Text") {
        console.log(node.getText(sourceFile));
        const cid = getStrAttr(node, "cid");
        const description = getStrAttr(node, "description");
        const fallback =
          getStrAttr(node, "fallback") ??
          (ts.isJsxOpeningElement(node) && getChildrenText(node));
        if (!fallback) {
          console.warn(
            `Using a <Text> component without a "fallback" attribute is never a good idea.`,
          );
          return;
        }

        if (!cid) {
          console.warn(
            `Using a <Text> component without a "cid" attribute is never a good idea.`,
          );
          return;
        }

        if (!description) {
          console.warn(
            `Using a <Text> component without a "description" attribute is never a good idea.`,
          );
        }
        const prev = textMap.get(cid);

        if (!prev || prev.description.length < (description?.length ?? 0)) {
          textMap.set(cid, { id: cid, description: description ?? "", content: fallback ?? "" });
        }
        return;
      }
    }

    // Detect t("cid", "fallback") or t("cid", "fallback", "description") — only in files that import useCopy
    if (
      importsCopy &&
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === "t" &&
      node.arguments.length >= 2 &&
      ts.isStringLiteral(node.arguments[0]) &&
      ts.isStringLiteral(node.arguments[1])
    ) {
      const cid = node.arguments[0].text;
      const fallback = node.arguments[1].text;
      const description =
        node.arguments.length >= 3 && ts.isStringLiteral(node.arguments[2])
          ? node.arguments[2].text
          : "";
      const prev = textMap.get(cid);
      if (!prev || prev.description.length < description.length) {
        textMap.set(cid, { id: cid, description, content: fallback });
      }
    }

    ts.forEachChild(node, walk);
  }

  function getStrAttr(
    node: ts.JsxOpeningLikeElement,
    name: string,
  ): string | undefined {
    for (const attr of node.attributes.properties) {
      if (
        ts.isJsxAttribute(attr) &&
        attr.name.getText(sourceFile) === name &&
        attr.initializer &&
        ts.isStringLiteral(attr.initializer)
      ) {
        return attr.initializer.text;
      }
    }
    return undefined;
  }
}

function getChildrenText(node: ts.JsxOpeningElement): string | undefined {
  // Walk UP from the opening element to its parent JsxElement
  const parent = node.parent;
  if (!ts.isJsxElement(parent)) return undefined;

  // parent.children is an array of JsxChild nodes
  const textChildren = parent.children.filter(ts.isJsxText);
  if (textChildren.length === 1) {
    return textChildren[0].text.trim();
  }
  return undefined;
}
